"""Core type definitions for the Polymarket trading bot."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"


class Outcome(Enum):
    YES = "YES"
    NO = "NO"


class OrderType(Enum):
    LIMIT = "LMT"
    MARKET = "MKT"
    GTC = "GTC"  # Good til cancelled
    GTD = "GTD"  # Good til date


class MarketStatus(Enum):
    ACTIVE = "active"
    CLOSED = "closed"
    RESOLVED = "resolved"
    ARCHIVED = "archived"


class SignalAction(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


class StrategyType(Enum):
    EDGE = "edge"
    MARKET_MAKING = "market_making"
    ARBITRAGE = "arbitrage"


class ExitReason(Enum):
    EDGE_GONE = "edge_gone"
    EDGE_DECAY = "edge_decay"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    TRAILING_STOP = "trailing_stop"
    RESOLUTION = "resolution"
    NEAR_RESOLUTION = "near_resolution"
    MANUAL = "manual"
    RISK_LIMIT = "risk_limit"
    ARBITRAGE = "arbitrage"
    MM_INVENTORY = "mm_inventory"


class OrderStatus(Enum):
    PENDING = "pending"
    OPEN = "open"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


@dataclass
class Market:
    """A Polymarket prediction market."""
    condition_id: str
    question: str
    description: str
    category: str
    end_date: Optional[datetime]
    tokens: dict  # {outcome: token_id} e.g. {"YES": "abc123", "NO": "def456"}
    active: bool = True
    volume: float = 0.0
    liquidity: float = 0.0
    last_price_yes: float = 0.5
    last_price_no: float = 0.5
    best_bid_yes: float = 0.0
    best_ask_yes: float = 1.0
    best_bid_no: float = 0.0
    best_ask_no: float = 1.0
    spread_yes: float = 1.0
    spread_no: float = 1.0
    resolution: Optional[str] = None  # "YES", "NO", or None
    tags: list = field(default_factory=list)
    updated_at: Optional[datetime] = None

    @property
    def yes_token_id(self) -> str:
        return self.tokens.get("YES", "")

    @property
    def no_token_id(self) -> str:
        return self.tokens.get("NO", "")

    @property
    def midpoint_yes(self) -> float:
        if self.best_bid_yes > 0 and self.best_ask_yes < 1:
            return (self.best_bid_yes + self.best_ask_yes) / 2
        return self.last_price_yes

    @property
    def hours_to_resolution(self) -> Optional[float]:
        if self.end_date is None:
            return None
        delta = self.end_date - datetime.now(timezone.utc)
        return max(0, delta.total_seconds() / 3600)


@dataclass
class ProbabilityEstimate:
    """Model's probability estimate for a market outcome."""
    market_id: str
    outcome: Outcome
    probability: float  # 0.0 to 1.0
    confidence: float  # 0.0 to 1.0
    reasoning: str
    model_name: str
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    sources: list = field(default_factory=list)

    @property
    def edge_vs_market(self) -> float:
        """Positive = model thinks market underprices this outcome."""
        return self.probability - self._market_price

    _market_price: float = 0.5

    def set_market_price(self, price: float):
        self._market_price = price


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    market_id: str
    action: SignalAction
    outcome: Outcome
    strategy: StrategyType
    price: float  # Target price
    size: float  # Dollar amount
    edge: float  # Estimated edge (model prob - market price)
    confidence: float
    reasoning: str
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict = field(default_factory=dict)


@dataclass
class Position:
    """An open position in a market."""
    market_id: str
    condition_id: str
    outcome: Outcome
    token_id: str
    side: Side
    entry_price: float
    size: float  # Number of shares/contracts
    cost_basis: float  # Total cost in USDC
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    strategy: StrategyType = StrategyType.EDGE
    opened_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_updated: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    peak_unrealized_pnl: float = 0.0
    low_edge_consecutive: int = 0
    entry_edge: float = 0.0  # Edge at entry time (model_prob - market_price)

    @property
    def market_value(self) -> float:
        return self.size * self.current_price

    def update_pnl(self, current_price: float):
        self.current_price = current_price
        self.unrealized_pnl = (current_price - self.entry_price) * self.size
        self.last_updated = datetime.now(timezone.utc)


@dataclass
class TradeResult:
    """Result of an executed trade."""
    market_id: str
    outcome: Outcome
    side: Side
    price: float
    size: float
    cost: float  # Total USDC spent/received
    fee: float
    order_id: Optional[str] = None
    strategy: StrategyType = StrategyType.EDGE
    exit_reason: Optional[ExitReason] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    paper: bool = True

    @property
    def net_cost(self) -> float:
        return self.cost + self.fee


@dataclass
class OrderBookLevel:
    """Single level in an order book."""
    price: float
    size: float


@dataclass
class OrderBook:
    """Order book for a token."""
    token_id: str
    bids: list  # List[OrderBookLevel], best first
    asks: list  # List[OrderBookLevel], best first
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def best_bid(self) -> float:
        return self.bids[0].price if self.bids else 0.0

    @property
    def best_ask(self) -> float:
        return self.asks[0].price if self.asks else 1.0

    @property
    def spread(self) -> float:
        return self.best_ask - self.best_bid

    @property
    def midpoint(self) -> float:
        if self.bids and self.asks:
            return (self.best_bid + self.best_ask) / 2
        return 0.5


@dataclass
class OpenOrder:
    """A resting limit order."""
    order_id: str
    market_id: str
    token_id: str
    outcome: Outcome
    side: Side
    price: float
    size: float
    filled_size: float = 0.0
    status: OrderStatus = OrderStatus.OPEN
    strategy: StrategyType = StrategyType.MARKET_MAKING
    placed_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def remaining_size(self) -> float:
        return self.size - self.filled_size

    @property
    def is_active(self) -> bool:
        return self.status in (OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED)
